### PR TITLE
[WIP] Create Gulp plugin for puli

### PR DESCRIPTION
**Pull request by mickaelandrieu**
Related ticket: puli/issues#88

Note this is not mergeable for now, it's only for discussing/debating purposes for now.

### CODE REVIEW

**Comment by webmozart** [comment]
Cool :) For a start, could you rebase onto master?

**Comment by mickaelandrieu** [comment]
ASAP :) today for sure !

**Comment by mickaelandrieu** [comment]
Ok, I realy need to rest today :/

I will try to have a functional plugin before sunday, for now I'm open to all comments, hints, tips you can have: I am new to puli (and I prefer cats :p) so I need your help :)

**Comment by webmozart** [comment]
This fixes puli/issues#88.

**Comment by webmozart** [comment]
Any update?

**Comment by mickaelandrieu** [comment]
Was expecting some comments :)  does this plug-in actually do what you expect for? 

How may we test?

**Comment by tgalopin** [comment]
I'll try this. Can you check how other plugins are being tested in JavaScript ?

**Comment by mickaelandrieu** [comment]
Yes,  I will review this by Saturday.  I'm still newbie to gulp ^^

**Comment by tgalopin** [comment]
No problem, just try to check the unit tests framework used in most plugins, it could help you implement tests :) .

**Comment by webmozart** [comment]
@mickaelandrieu any progress?

**Comment by mickaelandrieu** [comment]
@webmozart no sorry, I'm in the middle of relocation :/ if someone want to add tests, I'm ok. I can understand you can't wait for me, Puli needs to move on !

**Comment by Pierstoval** [comment]
Why not require a kind of configuration that will be loaded by the plugin?
At first sight, looks quite similar to what [Gryp.js](https://github.com/Orbitale/Gryp.js) does:
- Require a configuration file (or an on-the-fly configuration generated from Puli's config itself)
- Determine what files to concatenate/minify
- Potentially determine what filters to execute (flexibility) like `gulp-uglyfy`, etc. (indeed need to explain which Gulp components are supported)
- Execute them based on this config with a bunch of `gulpif()`s (with the associated plugin, checkout Gryp for this, it's used)
- Dump the outputs in the configured directory

What do you think?

**Comment by webmozart** [comment]
@Pierstoval @mickaelandrieu and I discussed this extensively. If we use a plugin _and_ a configuration file, we need to distribute the plugin separately and auto-generate the configuration file. Since the plugin will be very simple, it seemed easier and more performant to generate the plugin instead.

**Comment by mickaelandrieu** [comment]
@Pierstoval if you can finish this plugin, it's ok for me (as I don't have time for weeks :/). This would be nice, and I'm pretty new to gulp .

And ... @webmozart answered about the "config file + plugin" option :)

**Comment by florianeckerstorfer** [comment]
@webmozart asked me to chip in, since I have some experience with Gulp (but less so with Puli).

First of all, why do you have to generate the Gulp plugin with PHP? Couldn't you just read the mappings with JavaScript?

Bernhard asked me on how to test the plugin, well since you are using code generation you should verify that the generated code is correct. You are using no JavaScript code, just a few very basic calls to `gulp.src()`, `gulp.pipe()`,  `gulp.dest()` and `gulp.watch()` which are all tested in the Gulp code.

I think, at least as a start I would write the Gulp plugin as a simple wrapper for the CLI command. (Well, to be concrete, that is just Node.js code, no Gulp involved.)

``` javascript
require('child_process').exec('vendor/bin/puli publish --install', function(err, stdout, stderr) {
});
```

The problem with the current implementation is that when a mapping changes (and you are watching) you have to stop Gulp, regenerate the gulp-puli plugin and then start Gulp again.

**Comment by Pierstoval** [comment]
@webmozart & @mickaelandrieu : Actually, I was more thinking about retrieving Puli's configuration directly in your Gulpfile. 
So the plugin can then generate a Gulpfile based on a sample, and the JS inside this file would just retrieve Puli's configuration and dump resources based on it. It would avoid having to setup the Gulpfile manually after generating it (which is a pain when you have to create a Gulpfile for EVERY project. A config file is much better for convenience).

@florianeckerstorfer's proposal seems pertinent to me: why generate a javascript file with PHP? 
But the fact is that gulp _should_ be involved, else a "gulp plugin" makes no sense :smile:

**Comment by florianeckerstorfer** [comment]
@Pierstoval Thanks for agreeing with me; On the point of configuration files I have to disagree with you. The beauty and power (and I guess its popularity) is based on the fact that it is not a configuration file, but code. Grunt is basically a highly extensible configuration for building projects and Gulp is better (at least for me and those who prefer Gulp over Grunt) because it is more flexible. You can use something like [Yeoman](http://yeoman.io) to generate Gulpfiles for new projects if setting it up seems too much work.

**Comment by webmozart** [comment]
I'd like to prevent calling the `puli` CLI from the JS code since that will slow things down considerably. Also, the Puli configuration is not frequently being changed during development. Hence the slowdown doesn't really have benefits.

The most important aspect to me seems to be that development with Gulp stays efficient, i.e. Gulp runs quickly. The quickest solution seems to be to code-generate the plugin.

**Comment by webmozart** [comment]
@florianeckerstorfer Btw. I'd like to get rid of the `puli publish --install` command and replace it with Gulp completely, again for performance reasons.

**Comment by Pierstoval** [comment]
> The most important aspect to me seems to be that development with Gulp stays efficient, i.e. Gulp runs quickly. The quickest solution seems to be to code-generate the plugin.

Sometimes, Gulp (as well as Grunt or any other) can be very long, depending on your files, and especially when you have to run complex things in them. An example might be generating Bootstrap's css based on the less files, especially when you do it yourself adding a bunch of components to it plus your own design. As there will be many levels of import, if you also add an uglyfyer, autoprefixer, etc, it can take few seconds to work, but still it's efficient.

For the rest, I think I might have misunderstood what is the _real_ goal of the `gulp-plugin`, I'm a bit confused now :confused:

**Comment by florianeckerstorfer** [comment]
@webmozart But why not read the JSON config from Gulp?

Regarding performance: Gulp is fast because it uses streams, that is, it reads a file once and passes it through the build workflow and writes it at the end. The generated plugin does not offer this flexibility. That is, for example, if your stylesheet is Sass the Puli plugin would move the `.scss` to a directory and another Gulp task would convert it to CSS.

The "perfect" Puli plugin would allow to do this in one task. For example,

``` javascript
gulp.src(puli.src('/puli/demo-package/scss/**/*.scss'))
     .pipe(sass())
     .pipe(gulp.dest(puli.dest()));
```

**Comment by webmozart** [comment]
@florianeckerstorfer Because there's not just one JSON file to read, but many. Let me try to explain the asset management workflow with Puli. We need to consider two phases:

**Build Phase**

At first, assets of the current project are built, for example `res/scss/*.scss` => `res/public/css/`. The built assets are committed and distributed with the package.

The built assets are in the Puli repository now. So if you have a mapping `/app` => `res/`, you can do this in your template:

``` html+jinja
<img src="{{ resource_url('/app/public/css/style.css') }}" />
```

**Install Phase**

Then, all assets of all packages are published to a public directory (the document root), e.g.

```
res/public/* => public_html/
vendor/author/foo/res/public/* => public_html/foo/
vendor/author/bar/res/public/* => public_html/bar/
...
```

Both phases should be executed automatically when doing `gulp watch`. So if you change an *.scss file, it should be compiled to `res/public/css/` and then copied/linked to the document root.

Phase 1 is configured manually in Gulpfile.js since it depends on the project.

Phase 2 should be handled automatically, since all the mappings are already configured in the puli.json files of the root package and all installed packages.

**Comment by webmozart** [comment]
Ah actually I'm wrong. The mappings are only configured in the root package, so there's indeed just the root puli.json to read.

**Comment by florianeckerstorfer** [comment]
Ok, I see your point. I guess the best course of action would be to implement the copying of resources in pure Node.js since for the task at hand you don't really require Gulp and if the library is in Node you can pretty easily write wrappers for Gulp, Grunt, Broccoli, whatever the newest build system is. I guess that people using a build system other than Gulp don't want to add Gulp to their dependencies just for "copying a few files."

**Comment by webmozart** [comment]
@florianeckerstorfer Wouldn't that mean that the library would always copy all the files? I want to make sure that only changed files are copied to `public_html`, which Gulp seems to do quite well. How would I do the same in a Node.js library?

**Comment by florianeckerstorfer** [comment]
@webmozart The current implementation does copy always all files. How this currently works is that @mickaelandrieu defines one task `publish` that copies all files for every mapping. When the `watch` task is started then all source files are watched and when one of them is changed the `publish` task is called and **all** resources are copied to the target directory.

Example:

``` javascript
gulp.task('js', function () {
    gulp.src('js/**/*.js')
        .pipe(gulp.dest('public/js'));
});

gulp.task('watch', function () {
    gulp.watch('js/**/*.js', ['js']);
});
```

When you change one of the `.js` files in the `js/`directory all the `.js` files are copied into `public/js`. This works this way because in most cases when a file changes we want to execute a task. For example, when the _js_ task not only copies the files to the target directory but also concatenates them.

However, you can, of course get the file name of the changed file. The following code would just copy the changed file

``` javascript
gulp.watch('**/*.js').on(function (event) {
    fs.createReadStream(event.path).pipe(fs.createWriteStream(getDestPath(event.path)));
});
```

**Comment by florianeckerstorfer** [comment]
As you can see the actual copying does not require Gulp in this case. However, we would need a way in JavaScript to build the target directory based on the source directory.

For a Node library we could put the copying code in a function and call the function from the watch task the in different build system plugins. The actual code for copying and retrieving the target directory can be build-system-independent.

**Comment by florianeckerstorfer** [comment]
Another thing I should mention is that Gulp uses [vinyl-fs](https://www.npmjs.com/package/vinyl-fs) internally for the `src()` and `dest()` functions ([literally use them](https://github.com/gulpjs/gulp/blob/master/index.js#L25-L26)) and we could use the vinyl-fs library in the Puli Node library.

**Comment by Pierstoval** [comment]
So IIRC the `gulp-plugin` is ought to replace the `puli publish` command?

**Comment by webmozart** [comment]
Thanks for all that input @florianeckerstorfer! Maybe creating a `puli.js` Node library indeed is the best solution.

@Pierstoval The `puli publish --install` command only. We still need to map assets to servers in Puli to be able to generate URLs correctly.

**Comment by florianeckerstorfer** [comment]
I looked a little bit more into this how we could implement something like this. I believe it would require the following steps:
1. Read the `puli.json`
2. Build a list of path-to-path mappings, that is, replace the prefix in `path-mappings` with `extra.servers.*.document-root`
3. Provide ways to copy files from source to all dests.

For the last part I would propose the following API:
- `puli.dest()`: a function that takes a path and returns the target path(s) based on the mappings
- `puli.publish()`: a function that copies a file to all target paths
- `puli.src()`: a function that returns a glob with all Puli managed resources

Using this API we could build the following Gulpfile:

``` javascript
var puli = require('puli').create('puli.json');
gulp.task('puli', function () {
    gulp.src(puli.src())).pipe(gulp.dest(puli.publish()));
    gulp.watch(puli.src()).on(function (event) {
        puli.publish(event.path);
    });
});
```

**Comment by webmozart** [comment]
Interesting, thanks! I did some tinkering as well and came up with the following "optimal" Gulpfile.js: (I'm focusing on Gulp for now, we can abstract everything later)

``` js
gulp.task('default', [/* ... */, 'install', 'install-deps']);

gulp.task('install', function () {
    gulp.src('res/public/**').pipe(gulp.dest('web/'));
});

gulp.task('install-deps', function () {
    // for each mapping <vendor/package> => <target-dir>
    gulp.src('<vendor/package>/res/public/**').pipe(gulp.dest('web/<target-dir>/'));
});

gulp.task('watch', function () {
    gulp.watch('res/public/**', ['install']);
    // ...
});
```

I separated "install" and "install-deps", since we don't need to watch files of the dependencies which should not normally change (unless someone does a `composer update`).

Furthermore, we need to think how exactly we want to map assets to public paths in the future. There are two options:
1. directory-based, e.g. `res/public` => `web/`
2. file-based, e.g. `res/public/**/*.jpg` => CDN

Method 1 is simple, but method 2 seems to be necessary to provide more flexibility when putting some files on a CDN. CDN's would need to be overridden to be put into a local directory on dev environments, e.g. `web/cdn/`.

If we support both ways, we could create a JSON file that contains all mappings from Puli-managed files to public directory paths:

``` json
{
    "res/public/css/style.css": "web/css/style.css",
    "res/public/js/script.js": "web/js/script.js",
    "res/public/images/banner.jpg": "web/cdn/images/banner.jpg",
    ...
}
```

That file could be processed by the JS package.

**Comment by webmozart** [comment]
Of course, we could also process puli.json and create the mapping in JS, but that seems like a lot of work that needs to be repeated for every new installation process (a lot when triggered by `gulp watch`).

**Comment by Pierstoval** [comment]
The `puli.json` file has to be retrieved each time you run a command, but if you are using `watch`, the file is still in the memory and therefore does not need to be reloaded, if it's what you mean. So you can generate the mapping one per command, which can be quite fast.

**Comment by florianeckerstorfer** [comment]
@webmozart Your code however, would trigger copying _all_ resources every time one file changes. Gulp has no "auto-copy-only-the-changed-file" functionality.

**Comment by webmozart** [comment]
@florianeckerstorfer Yes, I forgot to include the code you posted above for the watch task. :)

**Comment by florianeckerstorfer** [comment]
@webmozart You still need a function to determine the target path based on source path in JavaScript. Or you would have to add a watcher for every file and I'm not sure if that is performant in any way.

**Comment by webmozart** [comment]
What about something like:

``` js
gulp.task('default', [/* ... */, 'install']);

gulp.task('install', function () {
    gulp.src(puli.src('/**/public/**')).pipe(puli.dest());
});

gulp.task('watch', function () {
    gulp.watch('res/public/**').on(function (event) {
        gulp.src(event.path).pipe(puli.dest());
    });
    // ...
});
```

Where:
- `puli.src()` takes a Puli path/glob and returns the file paths of the matching files
- `puli.dest()` takes a file path and writes it to the matching public path

**Comment by webmozart** [comment]
Updated the sample in the previous comment.

**Comment by webmozart** [comment]
Hi guys, any update? I'd like to get this into the next release.

/cc @maciekpaprocki

**Comment by webmozart** [comment]
I thought about this quite a lot in the last days and think I have come up with a better and more decoupled solution. Please give me your feedback.

Summary: Puli should care much less about assets than it currently does. We can move this all to JavaScript, with an _optional_ implementation in PHP for those who dislike JavaScript tools/configuration.

For brevity, I'll only describe the intended JavaScript solution here. The basic idea is to manage assets in two steps:
1. Install assets to document root(s), generate their URLs and write a `url-manifest.json` (JavaScript)
2. Generate URLs by reading `url-manifest.json` (in PHP)

The second step is trivial, so I'll only describe the first one. Code tells more than thousand words:

#### Example 1: Local Assets

Gulpfile.js

``` js
var puli = require('puli');
// or
var puli = require('puli').setup('.puli/path-mappings.json');

var urls = require('puli-urls');

gulp.task('install', function () {
    puli.src('/app/public')
        .pipe(urls())
        .pipe(gulp.dest('web/'))
        .pipe(urls.manifest({
            merge: true
        })
        .pipe(gulp.dest('.puli/'));
});

gulp.task('vendors', function () {
    puli.src('/batman/blog/public')
        .pipe(urls())
        .pipe(gulp.dest('web/blog/'))
        .pipe(urls.manifest({
            merge: true,
            base: '/blog/'
        })
        .pipe(gulp.dest('.puli/'));
});
```

.puli/url-manifest.json

``` json
{
    "any": {
        "/app/public/css/style.css": "/css/style.css",
        "/app/public/js/script.js": "/js/script.js",
        "/batman/blog/public/img/logo.png": "/blog/img/logo.png"
    }
}
```

#### Example 2: Local Assets with Versioning

Gulpfile.js

``` js
var puli = require('puli');
var urls = require('puli-urls');
var rev = require('gulp-rev');

gulp.task('install', function () {
    puli.src('/app/public')
        .pipe(rev())
        .pipe(gulp.dest('web/'))
        // take rev-manifest.json as input for urls()
        .pipe(rev.manifest())
        .pipe(urls())
        .pipe(urls.manifest({
            merge: true
        })
        .pipe(gulp.dest('.puli/'));
});

gulp.task('vendors', function () {
    puli.src('/batman/blog/public')
        .pipe(rev())
        .pipe(gulp.dest('web/blog/'))
        .pipe(rev.manifest())
        .pipe(urls())
        .pipe(urls.manifest({
            merge: true,
            base: '/blog/'
        })
        .pipe(gulp.dest('.puli/'));
});
```

.puli/url-manifest.json

``` json
{
    "any": {
        "/app/public/css/style.css": "/css/style-1ea23d.css",
        "/app/public/js/script.js": "/js/script-e14fab.js",
        "/batman/blog/public/img/logo.png": "/blog/img/logo-eea43b.png"
    }
}
```

#### Example 3: Remote Assets

Gulpfile.js

``` js
var puli = require('puli');
var urls = require('puli-urls');

gulp.task('install', function () {
    puli.src('/app/public')
        .pipe(urls())
        .pipe(/* upload to CDN */)
        .pipe(urls.manifest({
            merge: true,
            base: 'http://cdn.example.com/'
        })
        .pipe(gulp.dest('.puli/'));
});

gulp.task('vendors', function () {
    puli.src('/batman/blog/public')
        .pipe(urls())
        .pipe(/* upload to CDN */)
        .pipe(urls.manifest({
            merge: true,
            base: 'http://cdn.example.com/blog/'
        })
        .pipe(gulp.dest('.puli/'));
});
```

.puli/url-manifest.json

``` json
{
    "http": {
        "/app/public/css/style.css": "http://cdn.example.com/css/style.css",
        "/app/public/js/script.js": "http://cdn.example.com/js/script.js",
        "/batman/blog/public/img/logo.png": "http://cdn.example.com/blog/img/logo.png"
    }
}
```

#### Example 4: Remote Assets with SSL Support

Gulpfile.js

``` js
var puli = require('puli');
var urls = require('puli-urls');

gulp.task('install', function () {
    puli.src('/app/public')
        .pipe(urls())
        .pipe(/* upload to CDN */)
        .pipe(urls.manifest({
            merge: true,
            base: ['http://cdn.example.com/', 'https://cdn.example.com/']
        })
        .pipe(gulp.dest('.puli/'));
});

gulp.task('vendors', function () {
    puli.src('/batman/blog/public')
        .pipe(urls())
        .pipe(/* upload to CDN */)
        .pipe(urls.manifest({
            merge: true,
            base: ['http://cdn.example.com/blog/', 'https://cdn.example.com/blog/']
        })
        .pipe(gulp.dest('.puli/'));
});
```

.puli/url-manifest.json

``` json
{
    "https": {
        "/app/public/css/style.css": "https://cdn.example.com/css/style.css",
        "/app/public/js/script.js": "https://cdn.example.com/js/script.js",
        "/batman/blog/public/img/logo.png": "https://cdn.example.com/blog/img/logo.png"
    },
    "http": {
        "/app/public/css/style.css": "http://cdn.example.com/css/style.css",
        "/app/public/js/script.js": "http://cdn.example.com/js/script.js",
        "/batman/blog/public/img/logo.png": "http://cdn.example.com/blog/img/logo.png"
    }
}
```

What do you think?

**Comment by Swader** [comment]
As one of the people who [hate NPM and all its tools with a passion](http://www.sitepoint.com/look-ma-no-nodejs-a-php-front-end-workflow-without-node/), I very much support the idea of moving PuliPHP as far away from JS-land as possible. It shouldn't care about assets at all.

**Comment by webmozart** [comment]
@Swader It needs to care about them when it comes to generating their URLs. That's something that you need to be able to do in PHP, and that's all that Puli should do.

**Comment by Swader** [comment]
Naturally, but imo that's the maximum of care that should be given on Puli's end. If someone wants to plug in some middleware to take care of processing in between targeting the resource and getting its URL back, by me that's fine if optional. But as an end user and stickler for cross-platform development, if I had to install Node just to use Puli in any default capacity, I wouldn't use Puli.

**Pull request closed without merging**
